source 'https://rubygems.org'
ruby '2.6.6'

gem 'rack', '>= 2.0.6'
gem 'octokit', '~> 4.6'
gem 'libxslt-ruby', '1.2.0'
gem 'libxml-ruby', '3.2.0'
gem 'licensee', '~> 8.7'
gem 'sequel', '~> 5.7'
gem 'pg'
